import CanvasTable from '@/components/table/canvas-table';

const data = [
  { id: 1, name: 'John Doe', age: 28 },
  { id: 2, name: 'Jane Smith', age: 34 },
  { id: 3, name: 'Alice Johnson', age: 45 },
  { id: 4, name: 'Bob Brown', age: 23 },
  { id: 5, name: 'Charlie White', age: 29 },
  { id: 6, name: 'Eva Green', age: 31 },
  { id: 7, name: 'Frank Miller', age: 42 },
  { id: 8, name: 'Grace Lee', age: 27 },
  { id: 9, name: 'Henry Wilson', age: 33 },
  { id: 10, name: 'Irene Davis', age: 38 },
  { id: 11, name: 'Jack Robinson', age: 25 },
  { id: 12, name: 'Karen Moore', age: 47 },
  { id: 13, name: 'Leo Taylor', age: 32 },
  { id: 14, name: 'Mia Anderson', age: 29 },
  { id: 15, name: 'Noah Clark', age: 36 },
  { id: 16, name: 'Olivia Martin', age: 24 },
  { id: 17, name: 'Paul Harris', age: 41 },
  { id: 18, name: 'Quinn Lewis', age: 28 },
  { id: 19, name: 'Ryan Young', age: 39 },
  { id: 20, name: 'Sara Walker', age: 30 },
  { id: 21, name: 'Tom Scott', age: 44 },
  { id: 22, name: 'Uma Garcia', age: 31 },
  { id: 23, name: 'Victor King', age: 26 },
  { id: 24, name: 'Wendy Adams', age: 37 },
  { id: 25, name: 'Xavier Hall', age: 43 },
  { id: 26, name: 'Yvonne Turner', age: 29 },
  { id: 27, name: 'Zach Brown', age: 35 },
  { id: 28, name: 'Amy Phillips', age: 27 },
  { id: 29, name: 'Ben Campbell', age: 40 },
  { id: 30, name: 'Chloe Ross', age: 33 },
  { id: 31, name: 'David Evans', age: 25 },
  { id: 32, name: 'Emily Parker', age: 31 },
  { id: 33, name: 'Fred Nelson', age: 46 },
  { id: 34, name: 'Gina Cooper', age: 28 },
  { id: 35, name: 'Harry Watson', age: 38 },
  { id: 36, name: 'Ivy Mitchell', age: 29 },
  { id: 37, name: 'Jason Reed', age: 34 },
  { id: 38, name: 'Kelly Price', age: 42 },
  { id: 39, name: 'Luke Morgan', age: 26 },
  { id: 40, name: 'Monica Bell', age: 39 },
  { id: 41, name: 'Nathan Cook', age: 31 },
  { id: 42, name: 'Olivia Bailey', age: 27 },
  { id: 43, name: 'Peter Wood', age: 44 },
  { id: 44, name: 'Quinn Ross', age: 30 },
  { id: 45, name: 'Rachel Gray', age: 36 },
  { id: 46, name: 'Steve Howard', age: 28 },
  { id: 47, name: 'Tina Ward', age: 41 },
  { id: 48, name: 'Ulysses Cox', age: 32 },
  { id: 49, name: 'Valerie Brooks', age: 29 },
  { id: 50, name: 'Will Powell', age: 37 },
  { id: 51, name: 'Xena Perry', age: 43 },
  { id: 52, name: 'Yuri Long', age: 25 },
  { id: 53, name: 'Zoe Butler', age: 34 },
  { id: 54, name: 'Aaron Foster', age: 30 },
  { id: 55, name: 'Betty Barnes', age: 45 },
  { id: 56, name: 'Carl Jenkins', age: 28 },
  { id: 57, name: 'Diana Russell', age: 33 },
  { id: 58, name: 'Eric Sullivan', age: 38 },
  { id: 59, name: 'Fiona Rogers', age: 26 },
  { id: 60, name: 'George Peterson', age: 39 },
  { id: 61, name: 'Helen Simmons', age: 31 },
  { id: 62, name: 'Ian Griffin', age: 42 },
  { id: 63, name: 'Julia Kelly', age: 27 },
  { id: 64, name: 'Kevin Cole', age: 36 },
  { id: 65, name: 'Linda Marshall', age: 29 },
  { id: 66, name: 'Mark Dixon', age: 47 },
  { id: 67, name: 'Nina Shaw', age: 32 },
  { id: 68, name: 'Oscar Wells', age: 24 },
  { id: 69, name: 'Pam Cruz', age: 41 },
  { id: 70, name: 'Quentin Webb', age: 30 },
  { id: 71, name: 'Rita Ferguson', age: 35 },
  { id: 72, name: 'Sam Warren', age: 28 },
  { id: 73, name: 'Tracy Harrison', age: 43 },
  { id: 74, name: 'Ursula Fleming', age: 27 },
  { id: 75, name: 'Vincent Gordon', age: 39 },
  { id: 76, name: 'Whitney Hicks', age: 31 },
  { id: 77, name: 'Xavier Ortiz', age: 44 },
  { id: 78, name: 'Yvette Lyons', age: 29 },
  { id: 79, name: 'Zach Walters', age: 36 },
  { id: 80, name: 'Amber Schwartz', age: 25 },
  { id: 81, name: 'Brad Pearson', age: 37 },
  { id: 82, name: 'Caitlin Robbins', age: 30 },
  { id: 83, name: 'Dean Bates', age: 42 },
  { id: 84, name: 'Erica Santos', age: 28 },
  { id: 85, name: 'Felix Harmon', age: 33 },
  { id: 86, name: 'Gwen Barber', age: 26 },
  { id: 87, name: 'Howard Romero', age: 40 },
  { id: 88, name: 'Iris Thornton', age: 32 },
  { id: 89, name: 'Joel Heath', age: 29 },
  { id: 90, name: 'Kara Weaver', age: 38 },
  { id: 91, name: 'Lance Hodges', age: 27 },
  { id: 92, name: 'Megan Carlson', age: 45 },
  { id: 93, name: 'Nolan Wilkins', age: 31 },
  { id: 94, name: 'Olivia Bridges', age: 24 },
  { id: 95, name: 'Preston Castillo', age: 39 },
  { id: 96, name: 'Quincy Tran', age: 34 },
  { id: 97, name: 'Renee Manning', age: 28 },
  { id: 98, name: 'Shane Chavez', age: 43 },
  { id: 99, name: 'Tanya Norris', age: 35 },
  { id: 100, name: 'Ulrich Meyer', age: 30 }
];
const columns = [
  { key: 'id', title: 'ID', width: 50 },
  { key: 'name', title: 'Name', width: 150 },
  { key: 'age', title: 'Age', width: 50 }
];

const CanvasTablePage = () => {
  return (
    <div>
      <h1>Canvas Table Page</h1>
      <p>This is the canvas table page.</p>
      <CanvasTable data={data} columns={columns} />
    </div>
  );
};

export default CanvasTablePage;
